### ISSUE TITLE
Which parameters JDK DTrace events have?

### ISSUE THREAD

**Issue by ValchukDmitry** [azul-research/jdk-tracing#4]

**Comment by ValchukDmitry** [comment]
You may recognize it using [iovisor](https://github.com/iovisor/bcc) tool `tplist` with `-vv` argument
example:
`sudo /usr/share/bcc/tools/tplist -p $(pidof java) -vv`

**Comment by AntonKozlov** [comment]
Good, thanks. Closing the issue, the info probably should end up in our docs
