### ISSUE TITLE
How to check methods compile time with using DTrace events and eBPF?

### ISSUE THREAD

**Issue by ValchukDmitry** [azul-research/jdk-tracing#5]

**Comment by ValchukDmitry** [comment]
You need compile jvm with `--enable-dtrace` configure flag.
Run your application with `-XX:+DTraceMethodProbes` jvm flag.
Then, you could trace your application using [this example](https://github.com/azul-research/jdk-tracing/blob/tracing/dev-tracing/eBPF_examples/eBPF_java_compile_time.py)

**Comment by AntonKozlov** [comment]
And this is really cool! This instruction certainly required be in docs :)
