### ISSUE TITLE
Existing DTrace probes + LTTng 2.11

### ISSUE THREAD

**Issue by drazumova** [azul-research/jdk-tracing#9]
Сейчас есть проблема с запуском. Если собирать как в [документации](https://lttng.org/docs/v2.11/#doc-building-from-source) без каких-либо дополнительных флагов.
`cd $(mktemp -d)`
`wget http://lttng.org/files/lttng-modules/lttng-modules-latest-2.11.tar.bz2`
`tar -xf lttng-modules-latest-2.11.tar.bz2 `
`cd lttng-modules-2.11.* `
`make`
`sudo make modules_install`
`sudo depmod -a` 

`cd $(mktemp -d) &&
wget http://lttng.org/files/lttng-ust/lttng-ust-latest-2.11.tar.bz2 &&
tar -xf lttng-ust-latest-2.11.tar.bz2 &&
cd lttng-ust-2.11.* &&
./configure &&
make &&
sudo make install &&
sudo ldconfig`

`cd $(mktemp -d) &&
wget http://lttng.org/files/lttng-tools/lttng-tools-latest-2.11.tar.bz2 &&
tar -xf lttng-tools-latest-2.11.tar.bz2 &&
cd lttng-tools-2.11.* &&
./configure &&
make &&
sudo make install &&
sudo ldconfig`
При попытке создать сессию выдается ошибка `Session name not found`. \
\
LTTng 2.10 собирается [аналогично](https://lttng.org/docs/v2.10/#doc-building-from-source), выводит такие же ошибки вида
`At main.c:160:`
`- SSL error:02001002:system library:fopen:No such file or directory: ../crypto/bio/bss_file.c:72`
`- SSL error:2006D080:BIO routines:BIO_new_file:no such file: ../crypto/bio/bss_file.c:79`
`sign-file: certs/signing_key.pem: No such file or directory`
но работает.

**Comment by AntonKozlov** [comment]
> При попытке создать сессию выдается ошибка `Session name not found`.

А можешь скопипастить полные команды как ты запускаешь? Именно создание сессии

**Comment by AntonKozlov** [comment]
Кстати, альтернатива -- забить на автоматическую поддержу USDT в lttng, и переписать USDT события в нашей жаве на генерацию lttng событий (из #2)

**Comment by drazumova** [comment]
Я пыталась так `lttng create`, `lttng create new-session` или `lttng create new-session --output=./output`

**Comment by AntonKozlov** [comment]
Упс, мы кажется не обсудили, как это решать. Здесь я просил скинуть полный лог, того что ты запускаешь, чтобы может быть свежим взглядом найти разницу между 2.10 и 2.11. 
Особенно интересно в контексте создания и использования сессии, раз `Session name not found`. Сообщение появляется при `enable-event` или `start`?

У меня в дистрибутиве уже можно поставить 2.11, вроде каких-то проблем я с ним не испытал.

Кстати, возможно модуль можно не собирать -- он же не относиться к dtrace трейспоинтам. Может хватить только ust и tools

**Comment by drazumova** [comment]
Работает пример
https://github.com/azul-research/jdk-tracing/commit/ceea36133e934a6b70c2df7bc3cf5b3fe405cfa7
